---
version: "2.1"
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Tijuana
    ports:
      - 5004:5000
    restart: unless-stopped
