services:
  samba:
    container_name: samba
    image: ciberbago/samba-auto
    volumes:
      - ${EXTERNO}:/mnt/jaime
    ports:
      - 445:445
      - 139:139
    environment:
      - user_count=1
      - user1=jaime
      - password1=15963pknht
      - sharename1=NAS
    restart: unless-stopped