version: '3.3'
services:
    libreddit:
        container_name: libreddit
        image: libreddit/libreddit
        ports:
            - '8085:8080'
        restart: unless-stopped
#another test kek
