services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - ./data:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - /media/hdd:/media/hdd
      - /media/datos:/media/datos
    ports:
      - 3000:3000
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: 1gb #optional
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
