services:
  tasks.md:
    image: baldissaramatheus/tasks.md
    container_name: tasks.md
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/t:/tasks
      - ./data/config:/config
    restart: unless-stopped
    ports:
      - 3020:8080