services:
    filebrowser:
        container_name: filebrowser
        image: filebrowser/filebrowser
        volumes:
            - '/:/srv'
        ports:
            - '8088:80'
        restart: unless-stopped