---
version: '3.3'
services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - ./data:/config
      - ${EXTERNO}/comics:/data
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8081:8080
    # remove the whole environment section if you don't need it
    restart: unless-stopped
