---
version: '3.3'
services:
  komga:
    container_name: komga
    image: gotson/komga:latest
    volumes:
      - ./data:/config
      - ${EXTERNO}/comics:/data
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8081:25600
    restart: unless-stopped
