---
version: '3.3'
services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - type: bind
        source: ./data
        target: /config
      - type: bind
        source: ${EXTERNO}/comics
        #source: /home/jaime/media/comics
        target: /data
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    ports:
      - 8081:8080
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    restart: unless-stopped
