version: '2.3'

services:
  statping:
    container_name: statping
    image: adamboutcher/statping-ng:latest
    volumes:
      - ./data:/app
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9012:8080
    environment:
      DB_CONN: sqlite
    restart: always