version: "3"
services:
  navidrome:
    container_name: navi
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "${EXTERNO}/music:/music:ro"
    restart: always
