version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    volumes:
      - "./data:/data"
      - "${EXTERNO}/music:/music:ro"
    ports:
      - "4533:4533"
    environment:
      ND_SESSIONTIMEOUT: 168h
    user: 0:0
    restart: unless-stopped
    environment:
        ND_SESSIONTIMEOUT: 168h
