services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 81:3000
    volumes:
      - ./data:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integration
      - /media/hdd:/disk1:ro
    restart: unless-stopped
