version: '3.3'
services:
    jdownloader-2:
        container_name: jdownloader2
        ports:
            - '5800:5800'
        volumes:
            - './data:/config:rw'
            - '${EXTERNO}/downloads:/output:rw'
        image: jlesage/jdownloader-2
        environment:
            - DISPLAY_WIDTH=1920
            - DISPLAY_HEIGHT=925
