version: '3.3'
services:
    jdownloader-2:
        container_name: jdownloader2
        image: jlesage/jdownloader-2
        volumes:
            - './data:/config:rw'
            - '${EXTERNO}/descargas:/output:rw'
        ports:
            - '5800:5800'
        environment:
            - DISPLAY_WIDTH=1920
            - DISPLAY_HEIGHT=925
        restart: unless-stopped