version: '3.9'
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: WUD
    mem_limit: 128m
    mem_reservation: 50m
    cpu_shares: 256
    security_opt:
      - no-new-privileges=true
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/wud:/store
    ports:
      - 3555:3000
