services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 83:83/tcp
      - 53:53/udp
      #- 3111:3000 la primera vez que lo uses para instalar
    hostname: adguard
    restart: unless-stopped
