---
version: "3"
services:
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht:devel
    volumes:
      - /opt/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
