---
version: "2.1"
services:
  scrutiny:
    #image: lscr.io/linuxserver/scrutiny:version-145c819f
    image: lscr.io/linuxserver/scrutiny:060ac7b8-ls34
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Tijuana
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - ./data:/config
      - /run/udev:/run/udev:ro
    ports:
      - 8086:8080
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
    restart: always
