
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    ports:
      - "8080:8080" # webapp
      - "8086:8086" # influxDB admin
    devices:
      - "/dev/sda"
      - "/dev/nvme0n1"
    cap_add:
      - SYS_RAWIO
    restart: unless-stopped
