services:
    glances:
        container_name: glances
        image: nicolargo/glances:latest-full
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        ports:
            - '61208-61209:61208-61209'
        environment:
            - GLANCES_OPT=-w
        pid: host
        restart: unless-stopped