version: '3.3'
services:
    portainer-ce:
        ports:
            - '9000:9000'
        restart: unless-stopped
        container_name: portainer
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './data/portainer:/data'
        image: portainer/portainer-ce