---
services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    volumes:
      - ./data:/config
      - ${EXTERNO}:/data
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Tijuana
    devices:
      # VAAPI Devices (examples)
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri:/dev/dri
    restart: unless-stopped
