version: "3"
services:
  metube:
    container_name: metube
    image: alexta69/metube
    volumes:
      - ${EXTERNO}/videos:/downloads
      - ${EXTERNO}/music:/downloads/musica
    ports:
      - "3023:8081"
    restart: unless-stopped