
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    volumes:
      - ./data:/config
      - ${EXTERNO}/descargas:/app/qBittorrent/downloads
    ports:
      - "8113:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    restart: unless-stopped