version: '3.3'
services:
    bockiii:
        container_name: Deemix
        volumes:
            - './data:/config'
            - '${EXTERNO}/music:/downloads'
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK_SET=022
            - DEEMIX_SINGLE_USER=true
        ports:
            - '6595:6595'
        image: registry.gitlab.com/bockiii/deemix-docker
        restart: always
